import Link from "next/link";
import { DeleteItemButton } from "@/components/studio/delete-item-button";
import { requirePortfolioOwner } from "@/lib/auth";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";
import { PROJECT_COVER_MAX_SIZE_LABEL, PROJECT_GALLERY_MAX_SIZE_LABEL } from "@/lib/project-cover";

export const dynamic = "force-dynamic";

export default async function ProjectsPage({ searchParams }: { searchParams: Promise<{ saved?: string; deleted?: string; error?: string }> }) {
  await requirePortfolioOwner();
  const params = await searchParams;
  const admin = createSupabaseAdminClient();
  if (!admin) return <main className="min-h-svh"><div className="site-shell py-8 sm:py-10"><header className="flex flex-wrap items-center justify-between gap-4 border-b border-white/10 pb-6"><div><p className="eyebrow">Private dashboard</p><h1 className="mt-2 text-2xl font-medium tracking-[-0.04em] text-white">Projects</h1></div><div className="flex gap-3"><Link className="button-secondary" href="/studio">Dashboard</Link><Link className="button-primary" href="/studio/projects/new">New project</Link></div></header><section className="py-8"><p className="rounded-2xl border border-red-200/20 bg-red-200/10 p-4 text-sm text-red-100">Project content is unavailable until the Supabase admin environment variables are configured.</p></section></div></main>;
  const { data: projects } = await admin.from("projects").select("id, name, slug, is_published, sort_order").order("sort_order").order("updated_at", { ascending: false });
  const errorMessage = params.error === "invalid-project" ? "Complete all required fields: project name, type, year, summary, and order. A summary must be at least 20 characters." : params.error === "invalid-cover" ? `Cover image must be PNG, JPG, or WebP and no larger than ${PROJECT_COVER_MAX_SIZE_LABEL}.` : params.error === "gallery-migration-required" ? `Run supabase/project-gallery-migration.sql in Supabase before uploading screenshots. Images must be PNG, JPG, or WebP up to ${PROJECT_GALLERY_MAX_SIZE_LABEL}.` : params.error === "save-failed" ? "The project could not be saved. Check that its URL slug is unique and any links begin with https://." : params.error ? "The project could not be deleted. Try again." : null;
  return <main className="min-h-svh"><div className="site-shell py-8 sm:py-10"><header className="flex flex-wrap items-center justify-between gap-4 border-b border-white/10 pb-6"><div><p className="eyebrow">Private dashboard</p><h1 className="mt-2 text-2xl font-medium tracking-[-0.04em] text-white">Projects</h1></div><div className="flex gap-3"><Link className="button-secondary" href="/studio">Dashboard</Link><Link className="button-primary" href="/studio/projects/new">New project</Link></div></header>{params.saved && <p className="mt-6 rounded-lg border border-emerald-200/30 bg-emerald-200/10 p-3 text-sm text-emerald-100">Project saved.</p>}{params.deleted && <p className="mt-6 rounded-lg border border-emerald-200/30 bg-emerald-200/10 p-3 text-sm text-emerald-100">Project deleted.</p>}{errorMessage && <p className="mt-6 rounded-lg border border-red-200/20 bg-red-200/10 p-3 text-sm text-red-100">{errorMessage}</p>}<section className="py-8">{projects?.length ? <div className="divide-y divide-white/10 border-y border-white/10">{projects.map((project) => <article key={project.id} className="flex flex-wrap items-center justify-between gap-4 py-5"><div><p className="text-lg font-medium text-white">{project.name}</p><p className="mt-1 text-sm text-zinc-500">/{project.slug} · {project.is_published ? "published" : "draft"} · order {project.sort_order}</p></div><div className="flex items-center gap-3"><Link className="button-secondary" href={`/studio/projects/${project.id}`}>Edit</Link><DeleteItemButton id={project.id} title={project.name} type="project" /></div></article>)}</div> : <div className="rounded-2xl border border-white/10 bg-white/[0.025] p-8 text-zinc-400">No projects yet. Add ASCEND first, then DECIBEL and JOBO.</div>}</section></div></main>;
}
