import type { Metadata } from "next";
import { SiteFooter } from "@/components/site-footer";
import { SiteHeader } from "@/components/site-header";

export const metadata: Metadata = { title: "About | Shibil Mohammed", description: "About Shibil Mohammed, a full-stack developer from Kerala, India." };

export default function AboutPage() {
  return <main><div className="site-shell"><SiteHeader /><section className="py-20 sm:py-28"><p className="eyebrow">About me</p><h1 className="mt-5 max-w-5xl text-balance text-5xl font-medium tracking-[-0.06em] text-white sm:text-6xl md:text-7xl">Curious about systems. Calm in the middle of complexity.</h1><div className="mt-12 grid gap-8 md:grid-cols-[12rem_1fr]"><p className="eyebrow">The story so far</p><div className="max-w-2xl space-y-6 text-lg leading-8 text-zinc-300"><p>I have been drawn to technology since I was a kid—first through robotics and films, then through the first “Hello, World!” program I wrote on my laptop.</p><p>I started with C, moved through Java and Python, and found my place in web development. What began as curiosity became a genuine interest in turning ideas into things people can use.</p><p>I am an introvert who communicates clearly when it matters. I value trust, ownership, strong work, and being easy to work with. I also take the work seriously enough to keep it from making my brain blow up along the way.</p></div></div></section><section className="section-rule py-16 sm:py-20"><div className="grid gap-4 md:grid-cols-[12rem_1fr]"><p className="eyebrow">Experience</p><article className="border-l border-emerald-200/40 pl-5"><p className="text-sm text-zinc-500">Aug 2025 — Present · Calicut, Kerala</p><h2 className="mt-2 text-2xl font-medium text-white">Full Stack Developer · Bridgeon Solutions LLP</h2><p className="mt-4 max-w-2xl leading-7 text-zinc-400">An open-contribution environment where I have been able to explore problems, suggest solutions, review code, and take ownership beyond a single assigned task.</p></article></div></section><section className="section-rule py-16 sm:py-20"><div className="grid gap-4 md:grid-cols-[12rem_1fr]"><p className="eyebrow">Looking ahead</p><p className="max-w-2xl text-2xl leading-9 tracking-[-0.03em] text-zinc-200">I want to grow into an engineer who can contribute to scalable systems, meaningful products, and eventually businesses that solve useful problems.</p></div></section><SiteFooter /></div></main>;
}
