import Link from "next/link";
import { savePost } from "@/lib/studio-actions";

type Post = { id?: string; title?: string; slug?: string; excerpt?: string | null; body_markdown?: string; tags?: string[]; status?: "draft" | "published" };

export function PostEditor({ post = {} }: { post?: Post }) {
  const inputClass = "rounded-lg border border-white/15 bg-zinc-950 px-3 py-3 text-white outline-none transition placeholder:text-zinc-600 focus:border-emerald-200";
  return <form action={savePost} className="grid gap-6"><input type="hidden" name="id" value={post.id ?? ""} /><label className="grid gap-2 text-sm text-zinc-200">Title<input className={inputClass} name="title" defaultValue={post.title} required maxLength={140} /></label><label className="grid gap-2 text-sm text-zinc-200">URL slug <span className="text-zinc-500">Optional — created from the title when empty.</span><input className={inputClass} name="slug" defaultValue={post.slug} maxLength={160} placeholder="a-quiet-thought" /></label><label className="grid gap-2 text-sm text-zinc-200">Excerpt <span className="text-zinc-500">Optional short introduction.</span><textarea className={inputClass} name="excerpt" defaultValue={post.excerpt ?? ""} rows={3} maxLength={320} /></label><label className="grid gap-2 text-sm text-zinc-200">Writing <span className="text-zinc-500">Markdown is supported.</span><textarea className={`${inputClass} min-h-80 font-mono text-sm leading-7`} name="body" defaultValue={post.body_markdown} required /></label><label className="grid gap-2 text-sm text-zinc-200">Tags <span className="text-zinc-500">Separate with commas.</span><input className={inputClass} name="tags" defaultValue={post.tags?.join(", ")} placeholder="life, reflection" /></label><label className="grid gap-2 text-sm text-zinc-200">Visibility<select className={inputClass} name="status" defaultValue={post.status ?? "draft"}><option value="draft">Save as draft</option><option value="published">Publish now</option></select></label><div className="flex flex-wrap gap-3"><button className="button-primary" type="submit">Save post</button><Link className="button-secondary" href="/studio/posts">Cancel</Link></div></form>;
}
